Sisu specific PreConstruct/PreDestroy annotations
eclipse-sisu/sisu-project pull request #76
Opened 2023-02-15 09:34 UTC by cstamas

Just like other annotations like Typed, Priority add "own" annotations for Lifecycle as well (while do support JSR250 if present).

This closes #58

2023-02-18 07:00 UTC, kwin requested changes

2023-02-18 07:00 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/PostConstruct.java
> + * Copyright (c) 2010-present Sonatype, Inc.
Sonatype copyright?

2023-02-18 07:00 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/PostConstruct.java
> + *   Stuart McCulloch (Sonatype, Inc.) - initial API and implementation
Shouldn’t that be you @cstamas?

2023-02-18 07:00 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/bean/LifecycleBuilder.java
> +        boolean hasJsr250Lifecycle;
Rather `hasJsr250Annotations` as the lifecycle concept is applicable to both types of annotations

2023-02-18 07:00 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/bean/LifecycleModule.java
> + * {@link javax.annotation.PreDestroy} annotations. The lifecycle can be controlled with the associated {@link BeanManager}.
Or sisu lifecycle annotations!

2023-02-18 11:49 UTC, cstamas commented
Re copyright: am really unsure here, @mcculls ? The "old" files DO have these Sonatype headers, but am unsure why "newly added" files should carry as headers...

2023-02-18 11:59 UTC, cstamas commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/bean/LifecycleBuilder.java
> +        boolean hasJsr250Lifecycle;
fixed

2023-02-18 12:00 UTC, cstamas commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/bean/LifecycleModule.java
> + * {@link javax.annotation.PreDestroy} annotations. The lifecycle can be controlled with the associated {@link BeanManager}.
fixed, please reread

2023-02-18 15:18 UTC, mcculls commented
Hi @cstamas - for new files you can put your name under both the copyright and contributor lines, following the convention described in https://www.eclipse.org/projects/handbook/#ip-copyright-headers

2023-02-18 15:57 UTC, cstamas commented
Personally, but as practical option (as linked doco lists 4th bullet as optional), I'd rather do something like "Sisu Project" or nothing at all for 4th bullet, just standard eclipse header. Wdyt?

My thinking is toward simpler formatting/validation, but may be wrong in that respect...

2023-02-19 11:08 UTC, mcculls commented
Alternatively we could move to the more generic header and put copyright details in the `NOTICE` file - WDYT?
```
/********************************************************************************
 * Copyright (c) {year} Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * SPDX-License-Identifier: EPL-1.0
 ********************************************************************************/
```

2023-02-20 11:25 UTC, cstamas commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/PostConstruct.java
> + * Copyright (c) 2010-present Sonatype, Inc.
fixed

2023-02-20 11:25 UTC, cstamas commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/PostConstruct.java
> + *   Stuart McCulloch (Sonatype, Inc.) - initial API and implementation
fixed

2023-02-20 11:26 UTC, cstamas commented
Applied header @mcculls proposed

2023-02-26 13:17 UTC, kwin approved these changes

2023-02-26 14:55 UTC, mcculls approved these changes

2023-02-27 10:57 UTC, merged