Do not silently fail in case of class scanning exceptions
eclipse-sisu/sisu-project pull request #98
Opened 2023-10-17 17:44 UTC by kwin

This closes #97

2023-10-17 17:44 UTC, kwin commented
@cstamas Any idea how to make this configurable from Maven? Do we really want to extend the Plexus Container API for that?

2023-10-17 17:45 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/space/SisuIndex.java
> +            new SpaceScanner( _space, true ).accept( this );
I guess being always strict here should be fine

2023-10-17 17:45 UTC, kwin commented on org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/space/SpaceModule.java
> +        new SpaceScanner( space, finder, true ).accept( strategy.visitor( binder ) );
this should probably expose a way on how to toggle the strict flag.

2023-10-22 22:37 UTC, mcculls requested changes
I think the default mode should remain non-strict, for reasons discussed in https://github.com/eclipse/sisu.inject/issues/97#issuecomment-1774217953

We can still change the mode to strict when generating the index via annotation processing or the maven plugin. That should solve the main build-time issue without affecting runtime deployments.

2023-10-24 11:05 UTC, kwin commented
@mcculls Can you be more specific, where exactly you want to keep the default behaviour of being lenient?

1. https://github.com/eclipse/sisu.inject/blob/d2a7e64ad07a026ad488b042a37744e66ff9a75e/org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/space/SisuIndex.java#L95
2. https://github.com/eclipse/sisu.inject/blob/d2a7e64ad07a026ad488b042a37744e66ff9a75e/org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/space/SpaceModule.java#L169
3. https://github.com/eclipse/sisu.inject/blob/d2a7e64ad07a026ad488b042a37744e66ff9a75e/org.eclipse.sisu.inject/src/main/java/org/eclipse/sisu/space/QualifierCache.java#L83

or anywhere else (which I missed in the list above)

2023-11-12 07:23 UTC, kwin commented
@mcculls Can you comment on the individual cases listed above?

2024-01-07 15:48 UTC, mcculls commented
`SisuIndex` can be strict by default because it's build-time - everything else should be non-strict by default, with an option to make them strict.

2024-01-08 13:17 UTC, kwin commented
> everything else should be non-strict by default, with an option to make them strict.

@mcculls done now, can you check again?

2024-01-30 15:42 UTC, kwin commented
If there are no further concerns @mcculls I am gonna merge end of this week.

2024-02-03 10:26 UTC, merged